project:
  type: website

website:
  title: "Rimuksh Kansal's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/slbotbm
      - icon: linkedin
        href: https://www.linkedin.com/in/rimuksh-kansal/

format:
  html:
    theme: yeti
    css: styles.css



